### ISSUE TITLE
Broken on 0.3.15 latest release

### ISSUE THREAD

**Issue by shulcsm** [ohardy/dokku-volume#4]
Looks like affected by same issue. https://github.com/progrium/dokku/issues/906

**Comment by marblegravy** [comment]
Also seeing this and unable to rebuild an app with persistent volumes. Reading through the issue at progrium/dokku#906 I can't tell if this is supposed to be fixed or not... The issue was closed back on Feb 5 and the commit is tagged v0.3.15.

However, I'm currently running v0.3.15 and can't build/rebuild if I have volumes set up on an app.

**Comment by shulcsm** [comment]
This fork has fixes https://github.com/alessio/dokku-volume

**Comment by marblegravy** [comment]
Confirmed. The version at https://github.com/alessio/dokku-volume does work properly.

**Comment by ohardy** [comment]
Fixed with last merge, thanks to @alessio
